"""add reimbursement and software_tool

Revision ID: 6e25b8c33dfb
Revises: 706bbaa96f4d
Create Date: 2026-06-05 12:59:33.573207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e25b8c33dfb'
down_revision: Union[str, Sequence[str], None] = '706bbaa96f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
