"""add reimbursement and software_tool

Revision ID: 342c7e7dc486
Revises: 6e25b8c33dfb
Create Date: 2026-06-05 13:05:31.306154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342c7e7dc486'
down_revision: Union[str, Sequence[str], None] = '6e25b8c33dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
