"""create project tables

Revision ID: 395622aef0bf
Revises: 627b1a2f3fd4
Create Date: 2026-04-06 02:02:12.668549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395622aef0bf'
down_revision: Union[str, Sequence[str], None] = '627b1a2f3fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_company_name'), 'client', ['company_name'], unique=False)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('vendor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_id'), 'vendor', ['id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('owner_employee_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('budget_allocated', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_client_id'), 'project', ['client_id'], unique=False)
    op.create_index(op.f('ix_project_department_id'), 'project', ['department_id'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_owner_employee_id'), 'project', ['owner_employee_id'], unique=False)
    op.create_table('employee_project_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('billing_rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contribution_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_project_assignments_employee_id'), 'employee_project_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_project_assignments_id'), 'employee_project_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_employee_project_assignments_project_id'), 'employee_project_assignments', ['project_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_client_id'), 'invoice', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_project_id'), 'invoice', ['project_id'], unique=False)
    op.create_table('project_cost',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_cost_id'), 'project_cost', ['id'], unique=False)
    op.create_index(op.f('ix_project_cost_project_id'), 'project_cost', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_cost_vendor_id'), 'project_cost', ['vendor_id'], unique=False)
    op.create_table('project_revenue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('revenue_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recognized_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_revenue_client_id'), 'project_revenue', ['client_id'], unique=False)
    op.create_index(op.f('ix_project_revenue_id'), 'project_revenue', ['id'], unique=False)
    op.create_index(op.f('ix_project_revenue_invoice_id'), 'project_revenue', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_project_revenue_project_id'), 'project_revenue', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_revenue_project_id'), table_name='project_revenue')
    op.drop_index(op.f('ix_project_revenue_invoice_id'), table_name='project_revenue')
    op.drop_index(op.f('ix_project_revenue_id'), table_name='project_revenue')
    op.drop_index(op.f('ix_project_revenue_client_id'), table_name='project_revenue')
    op.drop_table('project_revenue')
    op.drop_index(op.f('ix_project_cost_vendor_id'), table_name='project_cost')
    op.drop_index(op.f('ix_project_cost_project_id'), table_name='project_cost')
    op.drop_index(op.f('ix_project_cost_id'), table_name='project_cost')
    op.drop_table('project_cost')
    op.drop_index(op.f('ix_invoice_project_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_client_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_employee_project_assignments_project_id'), table_name='employee_project_assignments')
    op.drop_index(op.f('ix_employee_project_assignments_id'), table_name='employee_project_assignments')
    op.drop_index(op.f('ix_employee_project_assignments_employee_id'), table_name='employee_project_assignments')
    op.drop_table('employee_project_assignments')
    op.drop_index(op.f('ix_project_owner_employee_id'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_department_id'), table_name='project')
    op.drop_index(op.f('ix_project_client_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_vendor_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index(op.f('ix_client_company_name'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
