"""Add analytics and intelligence domain models

Revision ID: 448944507e88
Revises: a327d6fb8210
Create Date: 2026-06-05 09:48:13.805658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '448944507e88'
down_revision: Union[str, Sequence[str], None] = 'a327d6fb8210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('rule_engine_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_engine_config_id'), 'rule_engine_config', ['id'], unique=False)
    op.create_index(op.f('ix_rule_engine_config_rule_name'), 'rule_engine_config', ['rule_name'], unique=True)
    op.create_table('user_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_id'), 'user_access', ['id'], unique=False)
    op.create_index(op.f('ix_user_access_user_id'), 'user_access', ['user_id'], unique=False)
    op.create_table('employee_revenue_attribution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('attributed_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('roi_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('utilization_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_revenue_attribution_employee_id'), 'employee_revenue_attribution', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_revenue_attribution_id'), 'employee_revenue_attribution', ['id'], unique=False)
    op.create_index(op.f('ix_employee_revenue_attribution_project_id'), 'employee_revenue_attribution', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_revenue_attribution_project_id'), table_name='employee_revenue_attribution')
    op.drop_index(op.f('ix_employee_revenue_attribution_id'), table_name='employee_revenue_attribution')
    op.drop_index(op.f('ix_employee_revenue_attribution_employee_id'), table_name='employee_revenue_attribution')
    op.drop_table('employee_revenue_attribution')
    op.drop_index(op.f('ix_user_access_user_id'), table_name='user_access')
    op.drop_index(op.f('ix_user_access_id'), table_name='user_access')
    op.drop_table('user_access')
    op.drop_index(op.f('ix_rule_engine_config_rule_name'), table_name='rule_engine_config')
    op.drop_index(op.f('ix_rule_engine_config_id'), table_name='rule_engine_config')
    op.drop_table('rule_engine_config')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
