"""Add BusinessRule

Revision ID: 6740036ca37d
Revises: 448944507e88
Create Date: 2026-06-08 19:08:58.932671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6740036ca37d'
down_revision: Union[str, Sequence[str], None] = '448944507e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rule',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_business_rule_rule_id'), 'business_rule', ['rule_id'], unique=False)
    op.create_index(op.f('ix_business_rule_rule_name'), 'business_rule', ['rule_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_rule_rule_name'), table_name='business_rule')
    op.drop_index(op.f('ix_business_rule_rule_id'), table_name='business_rule')
    op.drop_table('business_rule')
    # ### end Alembic commands ###
