"""add reimbursement and software_tool

Revision ID: 706bbaa96f4d
Revises: 395622aef0bf
Create Date: 2026-06-05 12:44:02.236982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706bbaa96f4d'
down_revision: Union[str, Sequence[str], None] = '395622aef0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reimbursement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursement_employee_id'), 'reimbursement', ['employee_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_expense_id'), 'reimbursement', ['expense_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_id'), 'reimbursement', ['id'], unique=False)
    op.create_table('software_tool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('annual_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_tool_department_id'), 'software_tool', ['department_id'], unique=False)
    op.create_index(op.f('ix_software_tool_id'), 'software_tool', ['id'], unique=False)
    op.create_index(op.f('ix_software_tool_name'), 'software_tool', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_tool_name'), table_name='software_tool')
    op.drop_index(op.f('ix_software_tool_id'), table_name='software_tool')
    op.drop_index(op.f('ix_software_tool_department_id'), table_name='software_tool')
    op.drop_table('software_tool')
    op.drop_index(op.f('ix_reimbursement_id'), table_name='reimbursement')
    op.drop_index(op.f('ix_reimbursement_expense_id'), table_name='reimbursement')
    op.drop_index(op.f('ix_reimbursement_employee_id'), table_name='reimbursement')
    op.drop_table('reimbursement')
    # ### end Alembic commands ###
