import { z } from 'zod'

/**
 * Allowed blog tag types
 */
export const BLOG_TAG_TYPES = [
  'Technology',
  'AI & Machine Learning',
  'Data Engineering',
  'Cloud',
  'DevOps',
  'Product',
  'Case Study',
  'Tutorial',
  'News',
  'Other',
] as const

export type BlogTagType = (typeof BLOG_TAG_TYPES)[number]

/**
 * Branded type for blog slug
 */
export type BlogSlug = string & { readonly __brand: 'BlogSlug' }
export const createBlogSlug = (value: string): BlogSlug => value as BlogSlug

/**
 * Full Blog schema — all fields returned from the DB
 */
export const BlogSchema = z.object({
  id: z.string().uuid('Invalid blog ID'),
  title: z.string().min(1, 'Title is required').max(255, 'Title must be less than 255 characters'),
  slug: z.string().min(1, 'Slug is required').max(255, 'Slug must be less than 255 characters'),
  description: z.string().max(500, 'Description must be less than 500 characters').nullable(),
  content: z.string().min(1, 'Content is required'),
  author: z.string().min(1, 'Author is required').max(255),
  featured_image: z.string().url('Invalid image URL').nullable(),
  published: z.boolean().default(false),
  tag_type: z.string().nullable(),
  is_featured: z.boolean().default(false),
  created_by: z.string().max(255).nullable(),
  updated_by: z.string().max(255).nullable(),
  created_at: z.string(),
  updated_at: z.string(),
})

export type Blog = z.infer<typeof BlogSchema>

/**
 * Input for creating a new blog (id, timestamps auto-generated by DB)
 */
export const BlogCreateInputSchema = z.object({
  title: z.string().min(1, 'Title is required').max(255),
  slug: z.string().min(1, 'Slug is required').max(255),
  description: z.string().max(500).optional().nullable(),
  content: z.string().min(1, 'Content is required'),
  author: z.string().min(1, 'Author is required').max(255),
  featured_image: z.string().url('Invalid image URL').optional().nullable(),
  published: z.boolean().default(false),
  tag_type: z.string().optional().nullable(),
  is_featured: z.boolean().default(false).optional(),
  created_by: z.string().max(255).optional().nullable(),
  updated_by: z.string().max(255).optional().nullable(),
})

export type BlogCreateInput = z.infer<typeof BlogCreateInputSchema>

/**
 * Partial update — all fields optional
 */
export const BlogUpdateInputSchema = BlogCreateInputSchema.partial()
export type BlogUpdateInput = z.infer<typeof BlogUpdateInputSchema>

/**
 * Paginated list response
 */
export const BlogListResponseSchema = z.object({
  blogs: z.array(BlogSchema),
  total: z.number().int().nonnegative(),
  page: z.number().int().positive(),
  limit: z.number().int().positive(),
})
export type BlogListResponse = z.infer<typeof BlogListResponseSchema>

/**
 * Query parameters for listing blogs
 */
export const BlogListQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(10),
  published: z.enum(['true', 'false', 'all']).default('true'),
  search: z.string().optional(),
  tag: z.string().optional(),
  tag_type: z.string().optional(),
})

export type BlogListQuery = z.infer<typeof BlogListQuerySchema>
