import type { Metadata } from 'next'
import { Bot, Zap, BookOpen, Database } from 'lucide-react'
import CopilotChat from '@/components/admin/copilot-chat'

export const metadata: Metadata = {
  title: 'AI Copilot - Admin Dashboard',
  description: 'Chat with your data using natural language — powered by the Brain AI Copilot',
}

const CAPABILITIES = [
  {
    icon: BookOpen,
    title: 'Natural Language Queries',
    desc: 'Ask plain English questions and get structured answers from your database.',
    color: 'bg-blue-50 border-blue-200 text-blue-700',
    iconBg: 'bg-blue-100',
  },
  {
    icon: Database,
    title: 'SQL Generation',
    desc: 'View the SQL query generated by the AI to understand exactly what data is fetched.',
    color: 'bg-indigo-50 border-indigo-200 text-indigo-700',
    iconBg: 'bg-indigo-100',
  },
  {
    icon: Zap,
    title: 'Action Mode',
    desc: 'Create, update, or delete records using natural language — with confirmation gates.',
    color: 'bg-orange-50 border-orange-200 text-orange-700',
    iconBg: 'bg-orange-100',
  },
]

export default function CopilotPage() {
  return (
    <div className="space-y-6 h-full flex flex-col">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 shrink-0">
        <div className="flex items-center gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#DC2626] shadow-md shrink-0">
            <Bot size={22} className="text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-[#1B2340]">AI Copilot</h1>
            <p className="text-sm text-[#6B7280] mt-0.5">
              Talk to your data in plain English — powered by the Brain AI engine
            </p>
          </div>
        </div>
      </div>

      {/* Capability cards */}
      <div className="grid sm:grid-cols-3 gap-4 shrink-0">
        {CAPABILITIES.map((cap) => (
          <div
            key={cap.title}
            className={`bg-white border rounded-xl p-4 flex items-start gap-3 shadow-sm hover:shadow-md transition-shadow ${cap.color.split(' ').slice(1).join(' ')}`}
          >
            <div className={`flex h-9 w-9 items-center justify-center rounded-lg ${cap.iconBg} shrink-0`}>
              <cap.icon size={17} className={cap.color.split(' ')[0].replace('bg', 'text').replace('-50', '-600')} />
            </div>
            <div>
              <p className="text-sm font-semibold text-[#1B2340]">{cap.title}</p>
              <p className="text-xs text-[#6B7280] mt-0.5 leading-relaxed">{cap.desc}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Chat interface — takes remaining space */}
      <div className="flex-1 min-h-0" style={{ minHeight: '500px' }}>
        <CopilotChat />
      </div>
    </div>
  )
}
